<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sandy" failures="1" tests="2" name="Test" time="0.05" errors="0" timestamp="2024-03-10T10:31:41 IST">
  <testcase classname="tests.TestngDemo" name="xyz" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at tests.TestngDemo.xyz(TestngDemo.java:84)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- xyz -->
  <testcase classname="tests.TestngDemo" name="sampleTest" time="0.001"/>
</testsuite> <!-- Test -->
